---

- hosts: all

  tasks: 
    - name: Ansible shell module multiple commands
      shell: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
    - name: Install reqired packages
      become: true
      become_method: sudo
      apt: 
        name: "{{ item }}" 
        state: present
      with_items:
        - nodejs
    - name: Install docker packages
      become: true
      become_method: sudo
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags:
        - docker
    - name: Add Docker s official GPG key
      become: true
      become_method: sudo
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker
    - name: Verify that we have the key with the fingerprint
      become: true
      become_method: sudo
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker
    - name: Set up the stable repository
      become: true
      become_method: sudo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes
      tags:
        - docker
    - name: Update apt packages
      become: true
      become_method: sudo
      apt:
        update_cache: yes
      tags:
        - docker
    - name: Install docker
      become: true
      become_method: sudo
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags:
        - docker
    - name: Add remote "ubuntu" user to "docker" group
      become: true
      become_method: sudo
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker
    - name: Install docker-compose
      become: true
      become_method: sudo
      get_url: 
        url : https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
    - name: Change docker-compose binary permission
      become: true
      become_method: sudo
      file:
        path: /usr/local/bin/docker-compose 
        owner: "ubuntu"
        group: "ubuntu"

