version: '3.8'
services:
  snake-game:
    build:
      context: ./
    volumes:
      - .:/usr/src/app
    command: npm run start
    ports:
      - "8085:7000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
